---
# ssh-pki/tasks/main.yml

ssh_pki_dir: "{{ playbook_dir }}/ssh_pki"
credentials_dir: "{{ playbook_dir }}/credentials"

# password on SSH CA
ssh_ca_phrase: "{{ lookup('password', credentials_dir ~ '/ssh_ca_phrase length=64') }}"

# ssh-keygen parameters
ssh_keytype: rsa
ssh_keysize: 4096

# name of master ssh key for this pod
pod_sshkey_name: "headnode"

# lists of keys to generate
ssh_client_genkeys:
  - name: "{{ pod_sshkey_name }}"

ssh_host_genkeys: []

