---
# copy-profile-playbook.yml
# Copies the profile to the head node

- name: Include vars
  hosts: head, config
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml

- name: Set hostvars with defaults for each node
  hosts: head, config
  roles:
    - hostvars-defaults

- name: Copy cord_profile to head node from config node
  hosts: head
  roles:
    - { role: copy-profile, become: yes }
    - { role: ssh-install, become: yes }
    - { role: glance-images, become: yes, when: on_maas }
    - { role: copy-credentials, become: yes, when: on_maas }

- name: Install ssh keys when using MaaS
  hosts: build
  roles:
    - { role: ssh-install-maas, become: yes, when: on_maas }

