---
# copy-cord-playbook.yml
# Copy the cord directory from config node to head node

- name: Include vars
  hosts: config
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml

- name: Copy cord directory structure to head node
  hosts: head
  roles:
    - copy-cord

