---
# cord-profile-playbook.yml

- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml

- name: Create CORD profile and copy Glance images
  hosts: head
  roles:
    - cord-profile
