---
# cord-config-playbook.yml
# Creates all configuration for a CORD pod

- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml

- name: Create SSL Root CA, Intermediate CA, Server certs, SSH CA and keypairs
  hosts: config
  roles:
    - { role: create-configdirs-become, when: create_configdirs_become | default(True) }
    - pki-root-ca
    - pki-intermediate-ca
    - pki-cert
    - ssh-pki

- name: Create CORD profile
  hosts: config
  roles:
    - cord-profile

