---
# onboard-exampleservice.yml
# Adds the exampleservice to the currently running pod

- name: Include vars
  hosts: head
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml

- name: Create exampleservice configuration
  hosts: head
  roles:
    - exampleservice-config
