---
# onos-debug-playbook.yml
# Enables app-specific debugging settings in ONOS

- name: Include vars
  hosts: head
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml

- name: Enable debugging for onos apps
  hosts: head
  roles:
    - onos-debug



