---
# opencloud-multi-playbook.yml
# Install an OpenCloud site, with multi-node Juju configured OpenStack

- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml

- name: Turn on virtualization
  hosts: all
  become: yes
    - dell-virt

- name: Check prerequisites
  hosts: all
  roles:
    - prereqs-common

- name: DNS Server and apt-cacher-ng Setup
  hosts: head
  become: yes
  roles:
    - dns-nsd
    - dns-unbound
    - apt-cacher-ng

- name: Use the new DNS server, prep systems
  hosts: all
  become: yes
  roles:
    - dns-configure
    - common-prep

- name: Configure head node, configure virtualization
  hosts: head
  roles:
    - { role: head-prep, become: yes }
    - { role: config-virt, become: yes }

- name: Create LXD's, Configure Juju, install XOS
  hosts: head
  roles:
    - create-lxd
    - onos-vm-install
    - juju-setup
    - juju-finish
    - cord-profile
    - xos-docker-images
    - xos-bootstrap
    - docker-compose
    - xos-head-start

- name: Configure compute nodes
  hosts: compute
  become: yes
  roles:
    - compute-prep

- name: Deploy compute nodes
  hosts: head
  roles:
    - juju-compute-setup

