---
# publish-platform-install-playbook.yml

- name: Include vars
  hosts: localhost
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml

- name: Publish the core image
  hosts: localhost
  roles:
    - xos-core-publish

