---
# start-xos-playbook.yml
# Start and configure XOS docker containers

- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml

- name: Start XOS containers with docker-compose
  hosts: head
  roles:
    - xos-up

