---
# teardown-openstack-playbook.yml

- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml

- name: Teardown CORD profile
  hosts: head
  roles:
   - teardown-openstack
