---
# vtn-refresh-playbook.yml
# Refreshes the VTN state, via the ONOS commandline

- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml

- name: Refresh VTN config
  hosts: head
  roles:
    - vtn-refresh
