#xos-volt-sync tests

- name: Check XOS VOLT Synchronizer Process
  shell: ps -f | grep "python volt-synchronizer.py -C /opt/xos/synchronizers/volt/volt_synchronizer_config"
  register: result
  until: result | success
  retries: 10
  delay: 5
  tags:
    - skip_ansible_lint # running a sub job

- name: Get Volume Mounts on XOS VOLT Synchronizer Container
  shell: mount -l | grep xos_services
  register: volumes
  tags:
    - skip_ansible_lint # running a sub job

- name: Validate Volume Mounts on XOS VOLT Synchronizer Container
  assert:
    that: "'/opt/xos_services/{{ item.name }}' in volumes.stdout|lower"
  with_items: "{{ xos_services }}"
  when:
    - "'{{ item.name }}' != 'vnodlocal'"
    - "'{{ item.name }}' != 'volt'"