---
# juju-setup/defaults/main.yml

# note: juju_config_path and charm_versions are also set in
# `juju-compute-setup/defaults/main.yml`.  Keep these in sync.

juju_config_path: /usr/local/src/juju_config.yml
charm_versions: {}

pki_dir: "{{ playbook_dir }}/pki"
credentials_dir: "{{ playbook_dir }}/credentials"

site_name: placeholder-sitename
site_suffix: "{{ site_name }}.test"

keystone_admin_password: "{{ lookup('password', credentials_dir ~ '/cord_keystone_admin chars=ascii_letters,digits') }}"

enable_dpdk: False
vcpu_pin_set: "^0,^2"
hugepages: "60%"
dpdk_socket_memory: "1024,0"
dpdk_lcore_mask: "0x1"
fabric_interfaces: "eth2"
pmd_cpu_mask: "0x2"
