---
# juju-setup/defaults/main.yml

# note: juju_config_path and charm_versions are also set in
# `juju-compute-setup/defaults/main.yml`.  Keep these in sync.

juju_config_path: /usr/local/src/juju_config.yml
charm_versions: {}

pki_dir: "{{ playbook_dir }}/pki"
