---
# juju-setup/defaults/main.yml

# note: juju_config_path and charm_versions are also set in
# `juju-compute-setup/defaults/main.yml`.  Keep these in sync.

juju_config_path: /usr/local/src/juju_config.yml
charm_versions: {}

pki_dir: "{{ playbook_dir }}/pki"

site_name: placeholder-sitename
site_suffix: "{{ site_name }}.test"

keystone_admin_password: "{{ lookup('password', credentials_dir ~ '/cord_keystone_admin chars=ascii_letters,digits') }}"
