---
# roles/cloudlab-prep/defaults/main.yml

cloudlab_extrafs:
  - { mount: /mnt/extra, dev: /dev/sdb }

cloudlab_links:
  - { src: /mnt/extra/lxc, dest: /var/lib/lxc  }
  - { src: /mnt/extra/lxd, dest: /var/lib/lxd  }
  - { src: /mnt/extra/nova, dest: /var/lib/nova }
  - { src: /mnt/extra/juju, dest: /var/lib/juju }
