---
# test-examplservice/tasks/main.yml
# Run tests to check that the single-node deployment has worked

- name: Load TOSCA to apply test config for ExampleService, over REST
  xostosca:
    url: "http://xos.{{ site_suffix }}:{{ xos_ui_port }}/api/utility/tosca/run/"
    user: "{{ xos_admin_user }}"
    password:  "{{ xos_admin_pass }}"
    recipe: "{{ lookup('file', cord_profile_dir + '/test-exampleservice.yaml' ) }}"

- name: Wait for ExampleService VM to come up
  shell: bash -c "source ~/admin-openrc.sh; nova list --all-tenants|grep 'exampleservice.*ACTIVE' > /dev/null"
  register: result
  until: result | success
  retries: 10
  delay: 60
  tags:
    - skip_ansible_lint # running a sub job

- name: Get ID of VM
  shell: bash -c "source ~/admin-openrc.sh; nova list --all-tenants|grep mysite_exampleservice|cut -d '|' -f 2"
  register: nova_id
  tags:
    - skip_ansible_lint # running a sub job

- name: Get mgmt IP of VM
  shell: bash -c "source ~/admin-openrc.sh; nova interface-list {{ nova_id.stdout }}|grep -o -m 1 '172\.27\.[[:digit:]]*\.[[:digit:]]*'"
  register: mgmt_ip
  tags:
    - skip_ansible_lint # running a sub job

- name: Get public IP of VM
  shell: bash -c "source ~/admin-openrc.sh; nova interface-list {{ nova_id.stdout }}|grep -o -m 1 '10\.6\.[[:digit:]]*\.[[:digit:]]*'"
  register: public_ip
  tags:
    - skip_ansible_lint # running a sub job

- name: Get name of compute node
  shell: bash -c "source ~/admin-openrc.sh; nova service-list|grep nova-compute|cut -d '|' -f 3"
  register: node_name
  tags:
    - skip_ansible_lint # running a sub job

- name: Wait for Apache to come up inside VM
  shell: ssh -o ProxyCommand="ssh -W %h:%p -l ubuntu {{ node_name.stdout }}" ubuntu@{{ mgmt_ip.stdout }} "ls /var/run/apache2/apache2.pid" > /dev/null
  register: result
  until: result | success
  retries: 20
  delay: 60
  tags:
    - skip_ansible_lint # running a sub job

- name: start container
  become: yes
  lxd_container:
    name: testclient
    state: started

- name: Make sure testclient has default route to vSG
  become: yes
  shell: lxc exec testclient -- route | grep default | grep "eth0.222.111"
  register: result
  until: result | success
  retries: 20
  delay: 30
  tags:
    - skip_ansible_lint # running a sub job

- name: Download the curl package through the vSG
  become: yes
  command: lxc exec testclient -- apt-get install -y curl
  tags:
    - skip_ansible_lint # running a sub job

# Don't use lxc_container in order to get output
- name: Test connectivity to ExampleService from test client
  become: yes
  command: lxc exec testclient -- curl -s http://{{ public_ip.stdout }}
  register: curltest
  tags:
    - skip_ansible_lint # running a sub job

- name: Output from curl test
  debug: var=curltest.stdout_lines

