---
# xos-service-onboard/defaults/main.yml

cord_dir: "{{ ansible_user_dir + '/cord' }}"

xos_bootstrap_ui_port: 9001

xos_libraries:
  - "ng-xos-lib"

xos_components:
  - name: gui-extensions-store
    recipe_filename: onboard-gui-extensions-store.yaml
  - name: Chameleon
    recipe_filename: onboard-chameleon.yaml
  - name: xos-ws
    recipe_filename: onboard-xos-ws.yaml
  - name: xos-gui
    recipe_filename: onboard-xos-gui.yaml

xos_services: []

