---
# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# prereqs-common/defaults/main.yml

min_memtotal_mb: 48000
min_processor_vcpus: 12

kvm_check: true

dns_check_domain: corddnscheck.opencord.org

# CNAME record for corddnscheck.opencord.org
dns_check_record: "wiki.opencord.org."

# obtained from: https://www.iana.org/domains/root/servers
dns_roots:
  - 192.5.5.241
  - 193.0.14.129
  - 198.41.0.4
  - 199.7.91.13

http_dl_url: "http://cord.staging.wpengine.com/wp-content/uploads/2016/07/cord-tm-logo.png"
http_dl_cksum: "sha256:9a69c741a4bb609ad7e49bd0fd335a95db2e66dc0d72866569e11385df9dcc28"

https_dl_url: "https://jenkins.opencord.org/static/8d0f081d/images/headshot.png"
https_dl_cksum: "sha256:690e82fb98ffb2b4b232d9b9cf9cc52eb7972e56a84902f6d1150b75456058c6"

