---
# teardown-openstack/tasks/main.yml

- name: Remove Juju directory
  file:
    path: "{{ ansible_user_dir }}/.juju"
    state: absent

- name: Remove containers for the OpenStack services
  become: yes
  lxd_container:
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ head_lxd_list }}"

