- name: Remove Juju directory
  file:
    path: "{{ ansible_user_dir }}/.juju"
    state: absent

- name: Remove containers for the OpenStack services
  become: yes
  lxd_container:
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ head_lxd_list }}"

- name: Remove PKI directories
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/cord/build/platform-install/pki/intermediate_ca
    - /opt/cord/build/platform-install/pki/root_ca
