---
# onos-cord-install/defaults/main.yml

# paths
pki_dir: "{{ playbook_dir }}/pki"
ssh_pki_dir: "{{ playbook_dir }}/ssh_pki"
head_onos_cord_dir: "/opt/onos_cord"

# ONOS docker image to use
pull_docker_registry: ""
pull_docker_tag: "candidate"
onos_docker_image: "{{ pull_docker_registry }}onosproject/onos:{{ pull_docker_tag }}"

# log level for ONOS
onos_log_level: "INFO"

# name of master ssh key for this pod
pod_sshkey_name: "headnode"

# used for Java KeyStore within ONOS image
trust_store_pw: 222222

# logging_host should be set to DNS or IP addr of logstash host
logging_host: "cordloghost"
log4j_port: 4560

