---
# onos-vm-install/defaults/main.yml

trust_store_pw: 222222

# ONOS 1.7 not tagged yet, but latest is 1.7
onos_docker_image: "onosproject/onos:latest"

onos_cord_dest: "{{ ansible_user_dir }}/onos-cord/"

node_private_key: "{{ ansible_user_dir }}/node_key"

# logging_host should be set to DNS or IP addr of logstash host
logging_host: "cordloghost"
log4j_port: 4560

