---
# monitoringservice-enable-inframonitoring/tasks/main.yml

- name: Run TOSCA to enable infra monitoring
  command: "python /opt/xos/tosca/run.py {{ xos_admin_user }} /opt/cord_profile/inframonitoring.yaml"
  tags:
    - skip_ansible_lint # TOSCA loading should be idempotent

