apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xos-core
  labels:
    app: xos-core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: xos-core
    spec:
      containers:
        - name: xos-core
          image: {{ .Values.images.xos_core.repository }}:{{ .Values.images.xos_core.tag }}
          # command: ["/bin/bash", "-c", "cd coreapi; ./start_coreapi.sh"]
          command: ["/bin/bash", "-c", "sleep 86400"]
          ports:
            - containerPort: 50051
              protocol: TCP
            - containerPort: 50055
              protocol: TCP
          volumeMounts:
            - name: xos-core-config
              mountPath: /opt/xos/xos_config.yaml
              subPath: config/xos_config.yaml
      volumes:
        - name: xos-core-config
          configMap:
            name: xos-core
            items:
             - key: config
               path: config/xos_config.yaml
