apiVersion: v1
kind: Service
metadata:
  name: "xos-db"
  labels:
    {{- include "xos-core.release_labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: "xos-db"
