---
# compute-node-config/defaults/main.yml

# location of cord_profile on head node
head_cord_profile_dir: /opt/cord_profile

# name of the external interface on compute nodes. Should have the ansible_ prefix.
# `fabric` is default in R-CORD
compute_external_interface: ansible_fabric

# service configs referenced here are likely located in cord-profile/templates
# used in openstack-compute-vtn.yaml.j2, referencing network in management-net.yaml.j2
use_management_hosts: False
vtn_management_host_net_interface: veth3

# used in openstack-compute-vtn.yaml.j2, referencing service in fabric.yaml.j2
use_fabric: False


