---
# xos-up/tasks/main.yml

- name: Create docker networks
  docker_network:
    name: "{{ item }}"
  with_items: "{{ xos_docker_networks }}"

- name: Bring up XOS services
  docker_service:
    project_name: "{{ cord_profile | regex_replace('\\W','') }}"
    project_src: "{{ head_cord_profile_dir }}"
