---
# monitoringservice-instantiate/tasks/main.yml

- name: Run TOSCA to instantiate monitoringservice
  command: "python /opt/xos/tosca/run.py {{ xos_admin_user }} /opt/cord_profile/monitoringservice.yaml"
  tags:
    - skip_ansible_lint # TOSCA loading should be idempotent

- name: Run TOSCA to instantiate monitoring channel
  command: "python /opt/xos/tosca/run.py {{ xos_admin_user }} /opt/cord_profile/monitoringtenant.yaml"
  tags:
    - skip_ansible_lint # TOSCA loading should be idempotent

