---
# monitoringservice-onboard/tasks/main.yml

- name: Disable onboarding
  command: "python /opt/xos/tosca/run.py {{ xos_admin_user }} /opt/cord_profile/disable-onboarding.yaml"
  tags:
    - skip_ansible_lint # TOSCA loading should be idempotent

- name: Have XOS container mount monitoringservice volume
  command: "python /opt/xos/tosca/run.py {{ xos_admin_user }} /opt/cord_profile/xos-monitoringservice.yaml"
  tags:
    - skip_ansible_lint # TOSCA loading should be idempotent

- name: Onboard monitoringservice
  command: "python /opt/xos/tosca/run.py {{ xos_admin_user }} /opt/cord_profile/monitoring-onboard.yaml"
  tags:
    - skip_ansible_lint # TOSCA loading should be idempotent

- name: Enable onboarding
  command: "python /opt/xos/tosca/run.py {{ xos_admin_user }} /opt/cord_profile/enable-onboarding.yaml"
  tags:
    - skip_ansible_lint # TOSCA loading should be idempotent

- name: Wait for monitoring to be onboarded
  uri:
    url: "http://localhost:{{ xos_bootstrap_ui_port }}/api/utility/onboarding/services/monitoring/ready/"
    method: GET
    return_content: yes
  register: xos_onboard_status
  until: '"true" in xos_onboard_status.content'
  retries: 60
  delay: 2

- name: Wait for XOS to be onboarded after monitoringservice onboarding
  uri:
    url: "http://localhost:{{ xos_bootstrap_ui_port }}/api/utility/onboarding/xos/ready/"
    method: GET
    return_content: yes
  register: xos_onboard_status
  until: '"true" in xos_onboard_status.content'
  retries: 60
  delay: 2

