---
# onos-fabric-install/tasks/main.yml

- name: Pull base docker image for ONOS
  docker_image:
    name: "{{ onos_docker_image }}"

- name: Create onos-fabric dest directory
  become: yes
  file:
    path: "{{ head_onos_fabric_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0755

- name: Create templated ONOS files
  template:
    src: "{{ item }}.j2"
    dest: "{{ head_onos_fabric_dir }}/{{ item }}"
  with_items:
    - docker-compose.yml

# Note: we do not rebuild onos container for the fabric

- name: Start ONOS for fabric
  docker_service:
    project_src: "{{ head_onos_fabric_dir }}"

