---
# ssh-install-maas/tasks/main.yml

# the following replicates the functionality of the maas repo `prep` role
# users/perms may seem off, but is identical to that role

- name: Create ssh key directory for MaaS
  when: on_maas
  file:
    dest: "/etc/maas/.ssh/"
    mode: 0755
    owner: "root"
    group: "root"
    state: directory

- name: Copy ssh private key for MaaS
  when: on_maas
  copy:
    src: "{{ ssh_pki_dir }}/client_certs/{{ pod_sshkey_name }}_sshkey"
    dest: "/etc/maas/.ssh/cord_rsa"
    mode: 0644
    owner: "root"
    group: "root"
    backup: true

- name: Copy ssh public key for MaaS
  when: on_maas
  copy:
    src: "{{ ssh_pki_dir }}/client_certs/{{ pod_sshkey_name }}_sshkey.pub"
    dest: "/etc/maas/.ssh/cord_rsa.pub"
    mode: 0644
    owner: "root"
    group: "root"
    backup: true

