---
# pull-xos-docker-images/tasks/main.yml

- name: Pull latest versions of images if not present
  docker_image:
    name: "{{ item }}:latest"
    repository: "{{ item }}:{{ deploy_docker_tag }}"
  with_items:
    - xosproject/vsg
    - redis

